In [110]:
import pandas as pd
import numpy as np
import re
import os
os.chdir('/home/ankushraut/Downloads/Thirio')

In [111]:
data = pd.read_csv('Dataset.csv')

In [112]:
data.describe()

,Age,BMI,Ticket Size,Window,Discount,Revenue,Arrival Latitude,Arrival Longitude,Departure Latitude,Departure Longitude,ETA,Curry,Spice,CustomerID
count,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000,2724.000000
mean,31.795521,21.478187,150.323054,24.359398,50.255507,74.726211,28.379959,77.094622,28.311000,77.106047,14.929148,12.540749,12.363803,50.555800
std,7.251049,2.492904,22.157879,13.697846,29.694034,46.543115,1.109071,1.200997,1.070968,1.209577,8.312067,6.913995,6.907884,28.640262
min,20.000000,13.590244,120.000000,1.000000,0.000000,0.000000,24.037673,73.210418,24.914313,73.317253,1.000000,1.000000,1.000000,1.000000
25%,25.000000,19.764989,140.000000,12.000000,24.000000,34.200000,27.638257,76.264202,27.589721,76.301303,8.000000,7.000000,6.000000,26.000000
50%,32.000000,21.483427,160.000000,24.000000,51.000000,72.000000,28.414528,77.093675,28.304019,77.087079,15.000000,13.000000,12.000000,51.000000
75%,38.000000,23.156524,160.000000,36.000000,76.250000,110.400000,29.111927,77.923360,29.037744,77.894939,22.000000,18.000000,18.000000,75.000000
max,44.000000,32.306078,180.000000,48.000000,100.000000,180.000000,32.966066,80.875479,32.346568,81.616149,29.000000,24.000000,24.000000,100.000000

In [113]:
positives = ['yes', 'yep', 'yeah', 'sure', 'yo', 'ordered before', 'ya']
negatives = ['nah', 'no', 'nope', 'never']
tracking = ['track', 'where', 'waiting', 'late', 'why']
cancellation = ["cancel", "don't deliver", "don't wanna eat"]
new_order = ['new', 'place', 'order']
def contains_word(text, corpus):
    for word in corpus:
        pattern = r'(^|[^\w]){}([^\w]|$)'.format(word)
        pattern = re.compile(pattern, re.IGNORECASE)
        matches = re.search(pattern, text)
        if bool(matches):
            break
    return bool(matches)

In [114]:
new_customer = input("Hi, I'm Thirio, your nutritional companion. Have you ordered from us before?")
if contains_word(new_customer, positives):
    customer_number = int(input('Welcome back! Please enter your unique ID. '))
else:
    print('Welcome to Thirio!')
    customer_number = len(data.CustomerID.unique())

Hi, I'm Thirio, your nutritional companion. Have you ordered from us before?Nope
Welcome to Thirio!

In [115]:
feedback_food = []
customer_id = []
feedback_delivery = []

flow1 = input('Do you want to place a new order or track your order?')
flow1_1 = input('Please enter the token number of your last order, if you have one.')

if contains_word(flow1, tracking):
    print('Your order ', data['Order Status'][int(flow1_1)])
    print('ETA ', data['ETA'][int(flow1_1)])

elif contains_word(flow1, cancellation):
    flow1_2 = input('Do you wanna cancel your order? ')
    if contains_word(flow1_2, positives):
        flow1_2_1 = input('Please enter your token number. ')
        if flow1_2_1.isdigit() == False or int(flow1_2_1) not in data.index:
            flow1_2_1 = input('Please enter a valid token number. ')
        print(data.Cancel[int(flow1_2_1)])

elif contains_word(flow1, new_order):
    new_token = len(data)-1
    rec = recommended(new_token)
    if len(rec[0]) != 0:
        print('We highly recommend you the following dishes:', rec[0])
    elif len(rec[1]) != 0:
        print('You could try these dishes:', rec[1])
    else:
        print('Wanna try one of these:', rec[2])
    flow1_3 = input('What would you like to order?')
    print('Thank you for ordering from Thirio! Your nutritious delicacy is en route!')

    
else:
    flow2 = input('Would you like to leave a feedback and help us improve?')
    if contains_word(flow2, positives):
        flow2_1 = int(input('Please rate the food quality and taste on a scale of 1-5. '))
        if flow2_1 == 5:
            print('We are privileged to have served you such tasty food.')
        elif flow2_1 == 4:
            flow2_1_1 = input('Please let us know how we can give you the best eating experience. ')
            feedback_food.append(flow2_1_1)
            customer_id.append(int(flow1_1))
        elif flow2_1 == 3:
            flow2_1_2 = input('Please let us know how we can go above average next time! ')
            feedback_food.append(flow2_1_2)
            customer_id.append(int(flow1_1))
        else:
            flow2_1_3 = input('Please help us know what went so wrong with the food. ')
            feedback_food.append(flow2_1_3)
            customer_id.append(int(flow1_1))
            print('We are really sorry you had to experience that. We would surely improve next time. ')
        
        flow2_2 = int(input('Please rate the delivery service on a scale of 1-5. '))
        if flow2_2 == 5:
            print('We are privileged to have served you so well!')
        elif flow2_2 == 4:
            flow2_2_1 = input('Please let us know how we can give you the best delivery service. ')
            feedback_delivery.append(flow2_2_1)
            customer_id.append(int(flow1_1))
        elif flow2_2 == 3:
            flow2_2_2 = input('Please let us know how we can improve our delivery service next time. ')
            feedback_delivery.append(flow2_2_2)
            customer_id.append(int(flow1_1))
        else:
            flow2_2_3 = input('Please help us know what went so wrong with the delivery. ')
            feedback_delivery.append(flow2_2_3)
            customer_id.append(int(flow1_1))
            print('We are really sorry you had to experience that. We would surely improve next time. ')
        print('Thanks for your valuable feedback!')
flow3 = input('Please let us know in case of any other grievances. ')
print("Thanks. We'll get back to you shortly.")

Do you want to place a new order or track your order?New order
Please enter the token number of your last order, if you have one.None
You could try these dishes: [93]
What would you like to order?Dal tadka
Thank you for ordering from Thirio! Your nutritious delicacy is en route!
Please let us know in case of any other grievances. None at the moment.
Thanks. We'll get back to you shortly.

In [116]:
data.head()

,Date,Day,Age,BMI,Sex,Ticket Size,Slab,Window,Discount,Revenue,...,Arrival Longitude,Departure Latitude,Departure Longitude,State Cuisine,Order Status,ETA,Curry,Spice,Cancel,CustomerID
0,4/1/2011,Fri,41,20.423548,F,140,L,23,72,39.2,...,78.379609,27.650275,77.034809,South India,is in the kitchen,28,23,6,The order has been cancelled.,78
1,4/1/2011,Fri,20,22.244202,F,140,M,47,80,28.0,...,75.618013,28.276404,77.745642,U.P.,is in the kitchen,18,1,4,"Sorry, the order can not be cancelled.",34
2,4/1/2011,Fri,24,21.369013,M,160,M,10,83,27.2,...,78.240014,28.182265,76.835473,J&K,is in the kitchen,9,5,3,The order has been cancelled.,15
3,4/1/2011,Fri,27,21.182299,M,120,M,22,92,9.6,...,77.333249,28.021881,77.549238,J&K,has been cancelled,9,5,7,"Sorry, the order can not be cancelled.",6
4,4/1/2011,Fri,22,18.087382,M,140,S,25,52,67.2,...,76.222159,27.101227,75.934964,Maharashtra,has been delivered,5,12,21,"Sorry, the order can not be cancelled.",51

In [117]:
#baseline recommendation
customer_data = data[(data.CustomerID == customer_number)].reset_index(drop = True)

state_preference = customer_data['State Cuisine'].value_counts().index
curry_preference = customer_data['Curry'].value_counts().index
spice_preference = customer_data['Spice'].value_counts().index

for i in range(len(state_preference)):
    if state_preference[i] not in data['State Cuisine'].tail(4):
        state_recommendation = state_preference[i]
    break

for i in range(len(curry_preference)):
    if curry_preference[i] not in data['Curry'].tail(4):
        curry_recommendation = curry_preference[i]
    break
    
for i in range(len(spice_preference)):
    if spice_preference[i] not in data['Spice'].tail(4):
        spice_recommendation = spice_preference[i]
    break

print('Based on your likes, we recommend', curry_recommendation, 'curry and', spice_recommendation, 'spices from', state_recommendation, '.')

Based on your likes, we recommend 15 curry and 1 spices from Punjab .

In [118]:
from sklearn.cluster import KMeans

In [119]:
from sklearn.preprocessing import LabelEncoder
lbl_sex = LabelEncoder()
lbl_day = LabelEncoder()
lbl_slab = LabelEncoder()
data.Sex = lbl_sex.fit_transform(data.Sex)
data.Day = lbl_day.fit_transform(data.Day)
data.Slab = lbl_slab.fit_transform(data.Slab)

In [120]:
#kmeans recommendation
kmeans_curry = KMeans(n_clusters = len(data.Curry.unique()), random_state = 0).fit(data.drop(labels = ['Date', 'Ticket Size',
                                                                                                      'CustomerID',
                                                                                                      'Cancel','Spice', 'ETA',
                                                                                                      'State Cuisine', 'Order Status',
                                                                                                      'Revenue', 'Discount'], axis = 1))
data['curry_cluster'] = pd.DataFrame({'curry_cluster':kmeans_curry.labels_})
unique_curry = []

for i in range(len(data.curry_cluster.unique())):
    unique_curry.append(np.sort(data.curry_cluster.unique())[i])

mode_curry = []
for i in unique_curry:
    curry_centered = data[(data.curry_cluster == i)]
    mode_curry.append(curry_centered.Curry.mode()[0])
    
recommended_curry = []
for i in range(len(data)):
    recommended_curry.append(mode_curry[data.curry_cluster[i]])

In [121]:
#kmeans recommendation
lbl_state = LabelEncoder()
data['State Cuisine'] = lbl_state.fit_transform(data['State Cuisine'])
kmeans_state = KMeans(n_clusters = len(data['State Cuisine'].unique()), random_state = 0).fit(data.drop(labels = ['Date', 'Ticket Size',
                                                                                                      'CustomerID',
                                                                                                      'Cancel','Spice', 'ETA',
                                                                                                      'Curry', 'Order Status',
                                                                                                      'Revenue', 'Discount'], axis = 1))
data['State Cuisine'] = lbl_state.inverse_transform(data['State Cuisine'])
data['state_cluster'] = pd.DataFrame({'state_cluster':kmeans_state.labels_})
unique_state = []

for i in range(len(data.state_cluster.unique())):
    unique_state.append(np.sort(data.state_cluster.unique())[i])

mode_state = []
for i in unique_state:
    state_centered = data[(data.state_cluster == i)]
    mode_state.append(state_centered['State Cuisine'].mode()[0])
    
recommended_state = []
for i in range(len(data)):
    recommended_state.append(mode_state[data.state_cluster[i]])

In [122]:
#kmeans recommendation
kmeans_spice = KMeans(n_clusters = len(data.Spice.unique()), random_state = 0).fit(data.drop(labels = ['Date', 'Ticket Size',
                                                                                                      'CustomerID',
                                                                                                      'Cancel','Curry', 'ETA',
                                                                                                      'State Cuisine', 'Order Status',
                                                                                                      'Revenue', 'Discount'], axis = 1))
data['spice_cluster'] = pd.DataFrame({'spice_cluster':kmeans_spice.labels_})
unique_spice = []

for i in range(len(data.spice_cluster.unique())):
    unique_spice.append(np.sort(data.spice_cluster.unique())[i])

mode_spice = []
for i in unique_spice:
    spice_centered = data[(data.spice_cluster == i)]
    mode_spice.append(spice_centered.Spice.mode()[0])
    
recommended_spice = []
for i in range(len(data)):
    recommended_spice.append(mode_spice[data.spice_cluster[i]])

In [123]:
dish = pd.read_csv('Dishes.csv')

In [124]:
dish.head()

   Dish  Curry  Spice State Cuisine
0     1     21      5        Punjab
1     2     17     23   South India
2     3      2     16   South India
3     4     22      7          U.P.
4     5     15     20   South India

In [125]:
def recommended(new_token):
    most_recommended = []
    moderately_recommended = []
    recommended = []
    for i in range(len(dish)):
        if dish.Curry[i] == recommended_curry[new_token] and dish.Spice[i] == recommended_spice[new_token] and dish['State Cuisine'][i] == recommended_state[new_token]:
            most_recommended.append(dish.Dish[i])
        elif dish.Curry[i] == recommended_curry[new_token] and dish.Spice[i] == recommended_spice[new_token]:
            moderately_recommended.append(dish.Dish[i])
        elif dish['State Cuisine'][i] == recommended_state[new_token] and dish.Spice[i] == recommended_spice[new_token]:
            moderately_recommended.append(dish.Dish[i])
        elif dish.Curry[i] == recommended_curry[new_token] and dish['State Cuisine'][i] == recommended_state[new_token]:
            moderately_recommended.append(dish.Dish[i])
        elif dish.Curry[i] == recommended_curry[new_token] and dish.Spice[i] != recommended_spice[new_token] and dish['State Cuisine'][i] != recommended_state[new_token]:
            recommended.append(dish.Dish[i])
        elif dish.Curry[i] != recommended_curry[new_token] and dish.Spice[i] == recommended_spice[new_token] and dish['State Cuisine'][i] != recommended_state[new_token]:
            recommended.append(dish.Dish[i])
        elif dish.Curry[i] != recommended_curry[new_token] and dish.Spice[i] != recommended_spice[new_token] and dish['State Cuisine'][i] == recommended_state[new_token]:
            recommended.append(dish.Dish[i])
    return most_recommended, moderately_recommended, recommended